version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: product-manager
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
