services:
  mariadb:
    image: mariadb:11.1.2
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - uek295_project_mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret123
      MYSQL_DATABASE: marjas
      MYSQL_USER: marjas
      MYSQL_PASSWORD: mychatpassword
    ports:
      - "3306:3306"

volumes:
  uek295_project_mariadb:
